backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/pages/index.astro"
        format: "yaml-frontmatter"
        editor:
          preview: false
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Subtitle", name: "heroSubtitle", widget: "string"}
          - {label: "Button Text", name: "buttonText", widget: "string"}
          - {label: "Button Link", name: "buttonLink", widget: "string", default: "#about"}
          - {label: "About Title", name: "aboutTitle", widget: "string"}
          - {label: "About Text", name: "aboutText", widget: "text"}